# BLANK CHECK referee: a C program for the Thru VM.
#   make                 -> build/thruvm/bin/blank_check_referee_c.bin
#   make -C test         -> host test (hash vectors + a full recorded game replayed through this program)
BASEDIR:=$(CURDIR)/build
THRU_C_SDK_DIR?=$(HOME)/.thru/sdk/c/thru-sdk
include $(THRU_C_SDK_DIR)/thru_c_program.mk
